### ISSUE TITLE
Dataset was invalid

### ISSUE THREAD

**Issue by huangzhazha** [andrea-zanella/keras-transfer-learning-inception-resnetv2#1]
Hello,The dataset was invalid,can you share again?thank you very much.

**Comment by andrea-zanella** [comment]
Hello, I couldn't find the same dataset. However, you can use the flower dataset in order to test it. Just make a folder, open a bash terminal (if you are on windows use the Git bash) in the folder and launch:
"curl -LO http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz"
Then you will have a flower dataset with 5 folders (the number of folders doesn't matter).
Let me know if it's working for you.
